name: Deploy Backend to Windows EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
    - name: Checkout backend code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install
      working-directory: C:\voedu\Voedu-backend

    - name: Run migrations (optional, if needed)
      run: npm run migrate
      working-directory: C:\voedu\Voedu-backend

    - name: Start backend (optional, for development)
      run: node server.js
      working-directory: C:\voedu\Voedu-backend
